name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - master
  workflow_dispatch: # Позволяет запускать этот экшен вручную кнопкой!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Если используете темы как субмодули

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.147.3'
          extended: true # Используйте extended-версию, если требует тема

      - name: Build Hugo
        run: hugo --cleanDestinationDir -s prebuild --ignoreCache && hugo  --cleanDestinationDir --minify 

#      - name: Deploy (пример)
#        run: |
#          # Здесь добавьте команды для деплоя собранной папки public/
#          # Например, копирование по SSH, на FTP или в продакшн-директорию
#          echo "Сайт успешно собран!"
#          

# 1. Добавляем SSH-ключ из секретов в Runner
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary # Пропускает проверку fingerprint (для локальных IP)
# --- ДОБАВЛЯЕМ УСТАНОВКУ RSYNC ---
      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      # 2. Выполняем rsync
      - name: Deploy via rsync
        run: |
          - name: Deploy via rsync
        run: |
          rsync -avzhe "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --exclude='.user.ini' --exclude='.htaccess' public/ root@192.168.50.105:/www/wwwroot/new.avtomoto25.cn.ua --delete